### ISSUE TITLE
http.Timeout custom value

### ISSUE THREAD

**Issue by ArisDBG** [cyberark/conjur-cli-go#150]
## Is your feature request related to a problem? Please describe.

conjur-cli requests time out after 10s. There is no way to adjust that value as of now.
This can cause problems when doing huge bulk changes which need more time to get processed by Conjur master.

Error Message: "Client.timeout exceeded while awaiting headers"

## Describe the solution you would like

Provide a parameter/ switch in conjur-cli to adjust the http.timeout value.
Ideally the value can be set in ".conjurrc" file and/or you ask for a custom time-out value during first cli init.

The change seems relative "easy" via adding the httpTimeout parameter to conjur-api config. 

## Describe alternatives you have considered

No alternative

## Additional context

No more context

**Comment by szh** [comment]
Hi @ArisDBG,
I think this is a sound idea. Are you interested in submitting a PR? I'm happy to direct you where in the codebase to look (hint: probably just adding a yaml property [here](https://github.com/cyberark/conjur-api-go/blob/main/conjurapi/config.go#L34))

**Comment by szh** [comment]
Completed in [v8.0.17](https://github.com/cyberark/conjur-cli-go/releases/tag/v8.0.17)!
